/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-D-Z-ABYATqmOYxYXvxulQE3SOg-P1mgfqLB0eDen-qOPHBGuOKrATgRM-U2UJJwRhzxmBd1SQzZIenyiZj5f-p6VXIUldfFMoCcmHNwKyd753xL49ZZHltiK",
  "tt": "tt-1-yLgM-T7orq7nqFtZJqViHJVM0tmxao5Z5au-Dxw5fZs=",
  "version": "2020-11-20"
}

export default ebconfig;